/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import java.awt.Font;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author hakankocak
 */
public class DoctorFrame extends javax.swing.JFrame{

    HospitalFrame hf = null;
    PatientFrame pf=null;
    /**
     * Creates new form DoctorFrame
     */
    public DoctorFrame(HospitalFrame h) {
        initComponents();
        setLocationRelativeTo(null);
        setSize(600,530);
        TextPrompt name = new TextPrompt("Name and Surname", nameTF);
        TextPrompt search = new TextPrompt("Name and Surname", searchTF);
        TextPrompt age= new TextPrompt("Age", ageTF);
        TextPrompt remove = new TextPrompt("Id of the Doctor", removeTF);
        age.changeAlpha(0.5f);
        age.changeStyle(Font.BOLD + Font.ITALIC);
        name.changeAlpha(0.5f);
        name.changeStyle(Font.BOLD + Font.ITALIC);
        search.changeAlpha(0.5f);
        search.changeStyle(Font.BOLD + Font.ITALIC);
        remove.changeAlpha(0.5f);
        remove.changeStyle(Font.BOLD + Font.ITALIC);
        hf=h;
        fillComboBox();
        pf= new PatientFrame(hf);
    }
    
    public void setTextArea()
    {
        textArea.setText("");
    }
    public void fillComboBox() {
        departmentsCB.setModel(new DefaultComboBoxModel(doctorSYS.getDepartmentNames()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        closeButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();
        DSYPanel = new javax.swing.JLabel();
        addPanel = new javax.swing.JPanel();
        nameTF = new javax.swing.JTextField();
        ageTF = new javax.swing.JTextField();
        maleRB = new javax.swing.JRadioButton();
        femaleRB = new javax.swing.JRadioButton();
        departmentsCB = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        sunCB = new javax.swing.JCheckBox();
        satCB = new javax.swing.JCheckBox();
        friCB = new javax.swing.JCheckBox();
        wedCB = new javax.swing.JCheckBox();
        monCB = new javax.swing.JCheckBox();
        thuCB = new javax.swing.JCheckBox();
        tueCB = new javax.swing.JCheckBox();
        addButton = new javax.swing.JButton();
        displayButton = new javax.swing.JButton();
        searchPanel = new javax.swing.JPanel();
        searchTF = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        removeTF = new javax.swing.JTextField();
        removeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Doctor Frame");

        closeButton.setText("Close");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        textArea.setColumns(20);
        textArea.setRows(5);
        jScrollPane1.setViewportView(textArea);

        DSYPanel.setText("Doctor System Panel");

        addPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("1. Add a Doctor"));

        nameTF.setToolTipText("");
        nameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTFActionPerformed(evt);
            }
        });

        ageTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageTFActionPerformed(evt);
            }
        });

        buttonGroup1.add(maleRB);
        maleRB.setSelected(true);
        maleRB.setText("M");

        buttonGroup1.add(femaleRB);
        femaleRB.setText("F");

        departmentsCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departmentsCBActionPerformed(evt);
            }
        });

        jLabel1.setText("Work Days:");

        sunCB.setText("Sun");

        satCB.setText("Sat");

        friCB.setText("Fri");

        wedCB.setText("Wed");

        monCB.setText("Mon");
        monCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monCBActionPerformed(evt);
            }
        });

        thuCB.setText("Thu");

        tueCB.setText("Tue");

        addButton.setText("ADD");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addPanelLayout = new javax.swing.GroupLayout(addPanel);
        addPanel.setLayout(addPanelLayout);
        addPanelLayout.setHorizontalGroup(
            addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addPanelLayout.createSequentialGroup()
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nameTF)
                            .addGroup(addPanelLayout.createSequentialGroup()
                                .addComponent(maleRB)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(femaleRB))
                            .addComponent(ageTF)
                            .addComponent(departmentsCB, javax.swing.GroupLayout.Alignment.TRAILING, 0, 159, Short.MAX_VALUE))
                        .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(addPanelLayout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jLabel1))
                            .addGroup(addPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(addPanelLayout.createSequentialGroup()
                                        .addComponent(wedCB)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(thuCB))
                                    .addGroup(addPanelLayout.createSequentialGroup()
                                        .addComponent(monCB)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tueCB))
                                    .addGroup(addPanelLayout.createSequentialGroup()
                                        .addComponent(friCB)
                                        .addGap(18, 18, 18)
                                        .addComponent(satCB))
                                    .addGroup(addPanelLayout.createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addComponent(sunCB))))))
                    .addGroup(addPanelLayout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(addButton)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        addPanelLayout.setVerticalGroup(
            addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addPanelLayout.createSequentialGroup()
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(monCB)
                            .addComponent(tueCB))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(wedCB)
                            .addComponent(thuCB))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(friCB)
                            .addComponent(satCB))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(addPanelLayout.createSequentialGroup()
                        .addContainerGap(30, Short.MAX_VALUE)
                        .addComponent(nameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(maleRB)
                            .addComponent(femaleRB))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ageTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(departmentsCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sunCB))
                        .addGap(4, 4, 4)))
                .addComponent(addButton)
                .addContainerGap())
        );

        displayButton.setText("Display Doctors");
        displayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayButtonActionPerformed(evt);
            }
        });

        searchPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Search Doctor"));

        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout searchPanelLayout = new javax.swing.GroupLayout(searchPanel);
        searchPanel.setLayout(searchPanelLayout);
        searchPanelLayout.setHorizontalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchTF, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(searchButton)
                .addContainerGap(81, Short.MAX_VALUE))
        );
        searchPanelLayout.setVerticalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchButton))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Remove a Doctor"));

        removeButton.setText("Remove");
        removeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(removeTF, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(removeButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(removeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(removeButton))
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(99, 99, 99)
                                .addComponent(DSYPanel))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addComponent(closeButton)
                                .addGap(43, 43, 43)
                                .addComponent(displayButton))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(searchPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(addPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DSYPanel)
                .addGap(18, 18, 18)
                .addComponent(addPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(searchPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(closeButton)
                    .addComponent(displayButton))
                .addGap(21, 21, 21))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        // TODO add your handling code here:
        dispose();
        hf.setVisible(true);
    }//GEN-LAST:event_closeButtonActionPerformed

    private void nameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTFActionPerformed

    private void ageTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ageTFActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        int[] work=new int[7];
        
        try{
            String name = nameTF.getText();
            int age = Integer.parseInt(ageTF.getText());
            String sex;
            if(maleRB.isSelected())
                sex="Male";
            else
                sex="Female";
            int departmentId = departmentsCB.getSelectedIndex();

            if(monCB.isSelected())
                work[0]=0;
            else
                work[0]=-1;
            if(tueCB.isSelected())
                work[1]=1;
            else
                work[1]=-1;
            if(wedCB.isSelected())
                work[2]=2;
            else
                work[2]=-1;
            if(thuCB.isSelected())
                work[3]=3;
            else
                work[3]=-1;
            if(friCB.isSelected())
                work[4]=4;
            else
                work[4]=-1;
            if(satCB.isSelected())
                work[5]=5;
            else
                work[5]=-1;
            if(sunCB.isSelected())
                work[6]=6;
            else
                work[6]=-1;
            doctorSYS.addDoctor(new Doctor(name, age, sex, departmentId, work));
            textArea.setText("Doctor is added.");
        }
        catch(NumberFormatException ex){
            ex.printStackTrace();
            textArea.setText("Please check the inputs.");
        }
        
        pf.fillComboBox();
        
    }//GEN-LAST:event_addButtonActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // TODO add your handling code here:
        String name = searchTF.getText();
        Doctor d=doctorSYS.getDoctor(name);
        if(d==null)
            textArea.setText("Doctor Couldnt Found");
        else
            textArea.setText("Informations: \n"+d.toString());
    }//GEN-LAST:event_searchButtonActionPerformed

    private void displayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayButtonActionPerformed
        // TODO add your handling code here:
        textArea.setText(doctorSYS.displayDoctors());
    }//GEN-LAST:event_displayButtonActionPerformed

    private void removeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonActionPerformed
        // TODO add your handling code here:
        
        int id = Integer.parseInt(removeTF.getText());
        if(doctorSYS.removeDoctor(id))
            textArea.setText("The doctor who has the\nid of "+id+" has been removed.");
        else
            textArea.setText("Doctor couldnt found.");
        
        doctorSYS.updateFile();
        
    }//GEN-LAST:event_removeButtonActionPerformed

    private void monCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_monCBActionPerformed

    private void departmentsCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departmentsCBActionPerformed
        // TODO add your handling code here:
        textArea.setText("The department of \nthe doctor will be: " +departmentsCB.getSelectedItem());
    }//GEN-LAST:event_departmentsCBActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DSYPanel;
    private javax.swing.JButton addButton;
    private javax.swing.JPanel addPanel;
    private javax.swing.JTextField ageTF;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton closeButton;
    private javax.swing.JComboBox<String> departmentsCB;
    private javax.swing.JButton displayButton;
    private javax.swing.JRadioButton femaleRB;
    private javax.swing.JCheckBox friCB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton maleRB;
    private javax.swing.JCheckBox monCB;
    private javax.swing.JTextField nameTF;
    private javax.swing.JButton removeButton;
    private javax.swing.JTextField removeTF;
    private javax.swing.JCheckBox satCB;
    private javax.swing.JButton searchButton;
    private javax.swing.JPanel searchPanel;
    private javax.swing.JTextField searchTF;
    private javax.swing.JCheckBox sunCB;
    private javax.swing.JTextArea textArea;
    private javax.swing.JCheckBox thuCB;
    private javax.swing.JCheckBox tueCB;
    private javax.swing.JCheckBox wedCB;
    // End of variables declaration//GEN-END:variables
}
